/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1;

import javax.swing.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.*;
import java.util.regex.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kshub
 */
public class BILLGENERATE extends javax.swing.JFrame {

    /**
     * Creates new form BILLGENERATE
     */
    public BILLGENERATE() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // </editor-fold>

    Connection con1;
    PreparedStatement insert;
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        txt_itemname = new javax.swing.JComboBox<>();
        txt_price1 = new javax.swing.JLabel();
        txt_itemname20 = new javax.swing.JComboBox<>();
        txt_itemname3 = new javax.swing.JComboBox<>();
        txt_itemname4 = new javax.swing.JComboBox<>();
        txt_itemname50 = new javax.swing.JComboBox<>();
        txt_itemname60 = new javax.swing.JComboBox<>();
        txt_itemname40 = new javax.swing.JComboBox<>();
        txt_price10 = new javax.swing.JLabel();
        txt_price40 = new javax.swing.JLabel();
        txt_price50 = new javax.swing.JLabel();
        txt_price60 = new javax.swing.JLabel();
        txt_price20 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setBackground(new java.awt.Color(202, 146, 146));
        jButton4.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        jButton4.setText("PRICE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 600, 141, 41));

        jTextField2.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 600, 89, 41));

        txt_itemname.setBackground(new java.awt.Color(202, 146, 146));
        txt_itemname.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        txt_itemname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "chicken", "mutton", "egg", "fish curry", "naan", "rice", "tea" }));
        txt_itemname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_itemnameActionPerformed(evt);
            }
        });
        jPanel1.add(txt_itemname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 197, 41));

        txt_price1.setBackground(new java.awt.Color(255, 255, 255));
        txt_price1.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        txt_price1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txt_price1, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 175, 66, 42));

        txt_itemname20.setBackground(new java.awt.Color(202, 146, 146));
        txt_itemname20.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        txt_itemname20.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "chicken", "mutton", "egg", "fish curry", "naan", "rice", "tea" }));
        txt_itemname20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_itemname20ActionPerformed(evt);
            }
        });
        jPanel1.add(txt_itemname20, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, 197, 41));

        txt_itemname3.setBackground(new java.awt.Color(202, 146, 146));
        txt_itemname3.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        txt_itemname3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "chicken", "mutton", "egg", "fish curry", "naan", "rice", "tea" }));
        txt_itemname3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_itemname3ActionPerformed(evt);
            }
        });
        jPanel1.add(txt_itemname3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 197, 41));

        txt_itemname4.setBackground(new java.awt.Color(202, 146, 146));
        txt_itemname4.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        txt_itemname4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "chicken", "mutton", "egg", "fish curry", "naan", "rice", "tea" }));
        txt_itemname4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_itemname4ActionPerformed(evt);
            }
        });
        jPanel1.add(txt_itemname4, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 277, 197, 0));

        txt_itemname50.setBackground(new java.awt.Color(202, 146, 146));
        txt_itemname50.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        txt_itemname50.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "chicken", "mutton", "egg", "fish curry", "naan", "rice", "tea" }));
        txt_itemname50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_itemname50ActionPerformed(evt);
            }
        });
        jPanel1.add(txt_itemname50, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 197, 40));

        txt_itemname60.setBackground(new java.awt.Color(202, 146, 146));
        txt_itemname60.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        txt_itemname60.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "chicken", "mutton", "egg", "fish curry", "naan", "rice", "tea" }));
        txt_itemname60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_itemname60ActionPerformed(evt);
            }
        });
        jPanel1.add(txt_itemname60, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 523, 197, 41));

        txt_itemname40.setBackground(new java.awt.Color(202, 146, 146));
        txt_itemname40.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        txt_itemname40.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "chicken", "mutton", "egg", "fish curry", "naan", "rice", "tea" }));
        txt_itemname40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_itemname40ActionPerformed(evt);
            }
        });
        jPanel1.add(txt_itemname40, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 197, 41));

        txt_price10.setBackground(new java.awt.Color(255, 255, 255));
        txt_price10.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        txt_price10.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txt_price10, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 235, 66, 43));

        txt_price40.setBackground(new java.awt.Color(255, 255, 255));
        txt_price40.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        txt_price40.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txt_price40, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 378, 66, 43));

        txt_price50.setBackground(new java.awt.Color(255, 255, 51));
        txt_price50.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        txt_price50.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txt_price50, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 312, 66, 43));

        txt_price60.setBackground(new java.awt.Color(255, 255, 255));
        txt_price60.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        txt_price60.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txt_price60, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 522, 66, 43));

        txt_price20.setBackground(new java.awt.Color(255, 255, 255));
        txt_price20.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        txt_price20.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txt_price20, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 448, 66, 43));

        jButton1.setBackground(new java.awt.Color(235, 148, 148));
        jButton1.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jButton1.setText("BILLING MANAGEMENT");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 420, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\kshub\\OneDrive\\Documents\\NetBeansProjects\\mavenproject1\\src\\image\\fish.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 70, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\kshub\\OneDrive\\Documents\\NetBeansProjects\\mavenproject1\\src\\image\\meat.png")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 50, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\kshub\\OneDrive\\Documents\\NetBeansProjects\\mavenproject1\\src\\image\\rice.png")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 70, 60));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\kshub\\OneDrive\\Documents\\NetBeansProjects\\mavenproject1\\src\\image\\tea.png")); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 60, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\kshub\\OneDrive\\Documents\\NetBeansProjects\\mavenproject1\\src\\image\\egg.png")); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 60, 60));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\kshub\\OneDrive\\Documents\\NetBeansProjects\\mavenproject1\\src\\image\\cooked chicken.png")); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 90, -1));

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\kshub\\OneDrive\\Documents\\NetBeansProjects\\mavenproject1\\src\\main\\java\\com\\mycompany\\mavenproject1\\icons8-back-arrow.gif")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\kshub\\OneDrive\\Documents\\NetBeansProjects\\mavenproject1\\src\\main\\java\\com\\mycompany\\mavenproject1\\forward-button.gif")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 0, 40, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 767, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_itemname40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_itemname40ActionPerformed
        String str = txt_itemname40.getSelectedItem().toString();
        int count = 0;
        if(str == "chicken"){
            count =1;
        } else if(str == "mutton"){
            count =2;
        } else if(str == "egg"){
            count =3;
        } else if(str == "fish curry"){
            count =4;
        } else if(str == "naan") {
            count =5;
        } else if(str == "rice"){
            count =6;
        } else if(str == "tea"){
            count =7;
        }

        //        int count = 0;
        try {
            //             String count;
            int c;
            Class.forName("com.mysql.jdbc.Driver");
            String url = "jdbc:mysql://localhost:3306/catering_man";
            String user = "root";
            String pwd = "";
            Connection con1 = DriverManager.getConnection(url, user, pwd);
            if (con1 != null) {

                String itemname = txt_itemname40.getSelectedItem().toString();
                String p = null;

                String query = "select price , sno from menu";

                PreparedStatement pat = con1.prepareStatement(query);
                ResultSet rs = pat.executeQuery();
                while (rs.next()) {

                    float f = rs.getFloat("price");
                    int i = rs.getInt("sno");
                    if (count == i) {

                        try {

                            String txt = Integer.toString((int) f );
                            txt_price40.setText(txt);

                            //                               System.out.println(sum);
                        } catch (Exception e) {

                        }
                    }

                }

                //
            }

        } catch (Exception ex) {
            Logger.getLogger(Display.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_txt_itemname40ActionPerformed

    private void txt_itemname60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_itemname60ActionPerformed
        String str = txt_itemname60.getSelectedItem().toString();
        int count = 0;
        if(str == "chicken"){
            count =1;
        } else if(str == "mutton"){
            count =2;
        } else if(str == "egg"){
            count =3;
        } else if(str == "fish curry"){
            count =4;
        } else if(str == "naan") {
            count =5;
        } else if(str == "rice"){
            count =6;
        } else if(str == "tea"){
            count =7;
        }

        //        int count = 0;
        try {
            //             String count;
            int c;
            Class.forName("com.mysql.jdbc.Driver");
            String url = "jdbc:mysql://localhost:3306/catering_man";
            String user = "root";
            String pwd = "";
            Connection con1 = DriverManager.getConnection(url, user, pwd);
            if (con1 != null) {

                String itemname = txt_itemname60.getSelectedItem().toString();
                String p = null;

                String query = "select price , sno from menu";

                PreparedStatement pat = con1.prepareStatement(query);
                ResultSet rs = pat.executeQuery();
                while (rs.next()) {

                    float f = rs.getFloat("price");
                    int i = rs.getInt("sno");
                    if (count == i) {

                        try {

                            String txt = Integer.toString((int) f );
                            txt_price60.setText(txt);

                            //                               System.out.println(sum);
                        } catch (Exception e) {

                        }
                    }

                }

                //
            }

        } catch (Exception ex) {
            Logger.getLogger(Display.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_txt_itemname60ActionPerformed

    private void txt_itemname50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_itemname50ActionPerformed
        String str = txt_itemname50.getSelectedItem().toString();

        int count = 0;
        if(str == "chicken"){
            count =1;
        } else if(str == "mutton"){
            count =2;
        } else if(str == "egg"){
            count =3;
        } else if(str == "fish curry"){
            count =4;
        } else if(str == "naan") {
            count =5;
        } else if(str == "rice"){
            count =6;
        } else if(str == "tea"){
            count =7;
        }

        //        int count = 0;
        try {
            //             String count;
            int c;
            Class.forName("com.mysql.jdbc.Driver");
            String url = "jdbc:mysql://localhost:3306/catering_man";
            String user = "root";
            String pwd = "";
            Connection con1 = DriverManager.getConnection(url, user, pwd);
            if (con1 != null) {

                String itemname = txt_itemname50.getSelectedItem().toString();
                String p = null;

                String query = "select price , sno from menu";

                PreparedStatement pat = con1.prepareStatement(query);
                ResultSet rs = pat.executeQuery();
                while (rs.next()) {

                    float f = rs.getFloat("price");
                    int i = rs.getInt("sno");
                    if (count == i) {

                        try {

                            String txt = Integer.toString((int) f );
                            txt_price50.setText(txt);

                            //                               System.out.println(sum);
                        } catch (Exception e) {

                        }
                    }

                }

                //
            }

        } catch (Exception ex) {
            Logger.getLogger(Display.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txt_itemname50ActionPerformed

    private void txt_itemname4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_itemname4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_itemname4ActionPerformed

    private void txt_itemname3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_itemname3ActionPerformed
        //String str = txt_itemname.getSelectedItem().toString();

        int count = 0;
        String str = txt_itemname3.getSelectedItem().toString();

        if(str == "chicken"){
            count =1;
        } else if(str == "mutton"){
            count =2;
        } else if(str == "egg"){
            count =3;
        } else if(str == "fish curry"){
            count =4;
        } else if(str == "naan") {
            count =5;
        } else if(str == "rice"){
            count =6;
        } else if(str == "tea"){
            count =7;
        }

        //        int count = 0;
        try {
            //             String count;
            int c;
            Class.forName("com.mysql.jdbc.Driver");
            String url = "jdbc:mysql://localhost:3306/catering_man";
            String user = "root";
            String pwd = "";
            Connection con1 = DriverManager.getConnection(url, user, pwd);
            if (con1 != null) {

                String itemname = txt_itemname3.getSelectedItem().toString();
                String p = null;

                String query = "select price , sno from menu";

                PreparedStatement pat = con1.prepareStatement(query);
                ResultSet rs = pat.executeQuery();
                while (rs.next()) {

                    float f = rs.getFloat("price");
                    int i = rs.getInt("sno");
                    if (count == i) {

                        try {

                            String txt = Integer.toString((int) f );
                            txt_price10.setText(txt);

                            //                               System.out.println(sum);
                        } catch (Exception e) {

                        }
                    }

                }

                //
            }

        } catch (Exception ex) {
            Logger.getLogger(Display.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txt_itemname3ActionPerformed

    private void txt_itemname20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_itemname20ActionPerformed
        String str = txt_itemname20.getSelectedItem().toString();
        int count = 0;
        if(str == "chicken"){
            count =1;
        } else if(str == "mutton"){
            count =2;
        } else if(str == "egg"){
            count =3;
        } else if(str == "fish curry"){
            count =4;
        } else if(str == "naan") {
            count =5;
        } else if(str == "rice"){
            count =6;
        } else if(str == "tea"){
            count =7;
        }

        //        int count = 0;
        try {
            //             String count;
            int c;
            Class.forName("com.mysql.jdbc.Driver");
            String url = "jdbc:mysql://localhost:3306/catering_man";
            String user = "root";
            String pwd = "";
            Connection con1 = DriverManager.getConnection(url, user, pwd);
            if (con1 != null) {

                String itemname = txt_itemname20.getSelectedItem().toString();
                String p = null;

                String query = "select price , sno from menu";

                PreparedStatement pat = con1.prepareStatement(query);
                ResultSet rs = pat.executeQuery();
                while (rs.next()) {

                    float f = rs.getFloat("price");
                    int i = rs.getInt("sno");
                    if (count == i) {

                        try {

                            String txt = Integer.toString((int) f );
                            txt_price20.setText(txt);

                            //                               System.out.println(sum);
                        } catch (Exception e) {

                        }
                    }

                }

                //
            }

        } catch (Exception ex) {
            Logger.getLogger(Display.class.getName()).log(Level.SEVERE, null, ex);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_txt_itemname20ActionPerformed

    private void txt_itemnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_itemnameActionPerformed
        // TODO add your handling code here:

        String str = txt_itemname.getSelectedItem().toString();
        int count = 0;
        if(str == "chicken"){
            count =1;
        } else if(str == "mutton"){
            count =2;
        } else if(str == "egg"){
            count =3;
        } else if(str == "fish curry"){
            count =4;
        } else if(str == "naan") {
            count =5;
        } else if(str == "rice"){
            count =6;
        } else if(str == "tea"){
            count =7;
        }

        //        int count = 0;
        try {
            //             String count;
            int c;
            Class.forName("com.mysql.jdbc.Driver");
            String url = "jdbc:mysql://localhost:3306/catering_man";
            String user = "root";
            String pwd = "";
            Connection con1 = DriverManager.getConnection(url, user, pwd);
            if (con1 != null) {

                String itemname = txt_itemname.getSelectedItem().toString();
                String p = null;

                String query = "select price , sno from menu";

                PreparedStatement pat = con1.prepareStatement(query);
                ResultSet rs = pat.executeQuery();
                while (rs.next()) {

                    float f = rs.getFloat("price");
                    int i = rs.getInt("sno");
                    if (count == i) {

                        try {

                            String txt = Integer.toString((int) f );
                            txt_price1.setText(txt);

                            //                               System.out.println(sum);
                        } catch (Exception e) {

                        }
                    }

                }

                //
            }

        } catch (Exception ex) {
            Logger.getLogger(Display.class.getName()).log(Level.SEVERE, null, ex);
        }

        //
    }//GEN-LAST:event_txt_itemnameActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
     
    }//GEN-LAST:event_jTextField2ActionPerformed

    private int generateRandomNumber() {
    // Generate a random number between 1 and 100 (inclusive)
     return ((int) (Math.random() * 5) + 8) * 50;
}
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int randomNum = generateRandomNumber();
    jTextField2.setText(String.valueOf(randomNum));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
billgenerating obj= new billgenerating();
obj.setVisible(true);
dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
Runnablefile obj = new Runnablefile();
obj.setVisible(true);
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BILLGENERATE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BILLGENERATE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BILLGENERATE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BILLGENERATE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BILLGENERATE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JComboBox<String> txt_itemname;
    private javax.swing.JComboBox<String> txt_itemname20;
    private javax.swing.JComboBox<String> txt_itemname3;
    private javax.swing.JComboBox<String> txt_itemname4;
    private javax.swing.JComboBox<String> txt_itemname40;
    private javax.swing.JComboBox<String> txt_itemname50;
    private javax.swing.JComboBox<String> txt_itemname60;
    private javax.swing.JLabel txt_price1;
    private javax.swing.JLabel txt_price10;
    private javax.swing.JLabel txt_price20;
    private javax.swing.JLabel txt_price40;
    private javax.swing.JLabel txt_price50;
    private javax.swing.JLabel txt_price60;
    // End of variables declaration//GEN-END:variables
}
